run:
  timeout: 5m
  skip-files: [ ]
  skip-dirs: [ ]

linters:
  enable-all: true
  disable:
    - deadcode
    - execinquery
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - structcheck
    - varcheck

    - cyclop
    - dupl
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - ginkgolinter
    - goerr113
    - gomnd
    - ifshort
    - lll
    - nilnil
    - nlreturn
    - paralleltest
    - prealloc
    - testpackage
    - tparallel
    - varnamelen
    - wrapcheck
    - wsl

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  goconst:
    min-len: 5
    min-occurrences: 3
  misspell:
    locale: US
  funlen:
    lines: -1
    statements: 40
  godox:
    keywords:
      - FIXME
  gofumpt:
    extra-rules: true
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - github.com/sirupsen/logrus
      - github.com/pkg/errors
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - sloppyReassign
      - rangeValCopy
      - octalLiteral
      - paramTypeCombine
    settings:
      hugeParam:
        sizeThreshold: 100
  tagliatelle:
    case:
      use-field-name: false
      rules:
        json: snake

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude:
    - "exported: exported type "
    - "G307:" # Deferring unsafe method "Close" on type "*os.File"
  exclude-rules:
    - path: '\\*_test.go'
      text: "G304:" # Potential file inclusion via variable
